### ISSUE TITLE
As a user, I can not specify priorityClassName to the deployed pods in the helm chart

### ISSUE THREAD

**Issue by andrew-e** [honeycombio/helm-charts#45]
I currently can not set the priority of the associated honeycomb pods that I have in my Kubernetes cluster, because I lack the ability to set them via passing it in as a value.

Can you please add this ability in your next release?

[An example of this in action](https://github.com/kedacore/charts/blob/master/keda/values.yaml)

Thanks.

**Comment by kthompson23** [comment]
This would be a helpful feature especially for the Honeycomb agent since it runs as a daemonset. I ran into an issue where I deployed all my services to a new cluster before deploying the Honeycomb agent. When deploying the agent, several of the pods were left in a _Pending_ state because some of the nodes had no free capacity. Since the Honeycomb agent pods and our service pods have the same default priority of _0_ the Honeycomb agent pod could not be scheduled without me manually scaling down the other pods.

The other daemonsets I run have their priority set higher than our service pods so they will always be scheduled even if he nodes have no capacity.
